targets:
  ubuntu-14.04:
  ubuntu-12.04:
  debian-7:
  debian-8:
  centos-6:
  centos-7:
dependencies:
  - git
before:
  - mv packager/Procfile .
  - mv packager/.godir .
after:
  - mv bin/main gogs
after_install: ./packager/debian/postinst
