targets:
  ubuntu-14.04:
    build_dependencies:
      - libpam0g-dev
    dependencies:
      - libpam0g
  ubuntu-12.04:
     build_dependencies:
      - libpam0g-dev
    dependencies:
      - libpam0g
  debian-7:
     build_dependencies:
      - libpam0g-dev
    dependencies:
      - libpam0g
  centos-6:
dependencies:
  - git
before:
  - mv packager/Procfile .
  - mv packager/.godir .
after:
  - mv bin/main gogs
after_install: ./packager/debian/postinst
